-- Thêm cột bật/tắt 2FA vào bảng TAIKHOAN
ALTER TABLE TAIKHOAN ADD COLUMN IF NOT EXISTS Is2FAEnabled BOOLEAN NOT NULL DEFAULT FALSE;

-- Tạo bảng OTP_2FA phục vụ cho luồng đăng nhập
CREATE TABLE IF NOT EXISTS OTP_2FA (
  MaOTP       SERIAL PRIMARY KEY,
  MaTK        INT NOT NULL REFERENCES TAIKHOAN(MaTK) ON DELETE CASCADE,
  OTPHash     VARCHAR(255) NOT NULL,
  TempToken   VARCHAR(255) NOT NULL UNIQUE,
  HetHan      TIMESTAMP NOT NULL,
  DaSuDung    BOOLEAN NOT NULL DEFAULT FALSE,
  NgayTao     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Index cho TempToken
CREATE INDEX IF NOT EXISTS idx_otp2fa_temptoken ON OTP_2FA(TempToken);
